i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
i_int:0 o_= v_int:567 sz_com
i_int:1 o_= v_int:25 sz_com
i_int:2 o_= i_int:0 o_+ i_int:1 sz_com
i_str:0 o_= sz_quo ahoj sz_quo sz_com
